import { Knex } from "knex";
import { ETableNames } from "../eTableNames";

export const seed = async (knex: Knex) => {
  const [{ count }] = await knex(ETableNames.cidade).count<[{ count: number }]>(
    "* as count"
  );
  if (!Number.isInteger(count) || Number(count) > 0) return;

  const cidadesToInsert = cidadesDeMinas.map((nomeDaCidade) => ({
    nome: nomeDaCidade,
  }));
  await knex(ETableNames.cidade).insert(cidadesToInsert);
};

const cidadesDeMinas = [
  "Abaeté",
  "Abre Campo",
  "Abreu e Lima",
  "Acaiaca",
  "Açucena",
  "Água Boa",
  "Aguanil",
  "Aguanil",
  "Aimorés",
  "Aiuruoca",
  "Alagoa",
  "Alagoa dos Patos",
  "Albertina",
  "Alfenas",
  "Alfredo Vasconcelos",
  "Almenara",
  "Alpinópolis",
  "Alvinópolis",
  "Alvorada de Minas",
  "Amparo do Serra",
  "Andradas",
  "Andrelândia",
  "Andrequicé",
  "Angelândia",
  "Antônio Carlos",
  "Antônio Dias",
  "Antônio Prado de Minas",
  "Aparaíso",
  "Araxá",
  "Araçuaí",
  "Araçaí",
  "Araciaba de Minas",
  "Arapongas",
  "Araporã",
  "Araçatiba",
  "Arceburgo",
  "Arcos",
  "Areado",
  "Argirita",
  "Aricanduva",
  "Aripuanã",
  "Aracitaba",
  "Arceburgo",
  "Arcos",
  "Areado",
  "Argirita",
  "Aricanduva",
  "Aripuanã",
  "Barão de Cocais",
  "Barbacena",
  "Barra Longa",
  "Barroso",
  "Belo Horizonte",
  "Berilo",
  "Betim",
  "Bicas",
  "Biquinhas",
  "Boa Esperança",
  "Bom Despacho",
  "Bom Jardim de Minas",
  "Bom Jesus da Penha",
  "Bom Jesus do Galho",
  "Bom Repouso",
  "Bonfinópolis de Minas",
  "Bonito de Minas",
  "Borda da Mata",
  "Botelhos",
  "Brasília de Minas",
  "Brasília Paulista",
  "Brasília de Minas",
  "Brasília Paulista",
  "Brumadinho",
  "Buenópolis",
  "Buritizeiro",
  "Buritis",
  "Cabeceira Grande",
  "Cachoeira da Prata",
  "Cachoeira de Minas",
  "Caetanópolis",
  "Caeté",
  "Caldas",
  "Caldas Novas",
  "Camanducaia",
  "Cambuí",
  "Campanha",
  "Cana Verde",
  "Candeias",
  "Capela Nova",
  "Capinópolis",
  "Caputira",
  "Caraí",
  "Carangola",
  "Carlos Chagas",
  "Carmésia",
  "Carmo da Mata",
  "Carmo do Cajuru",
  "Carmo do Rio Claro",
  "Carmo do Paranaíba",
  "Carneiropolis",
  "Carrancas",
  "Carvalhópolis",
  "Casa Grande",
  "Cascalho Rico",
  "Cataguases",
  "Catas Altas",
  "Catas Altas da Noruega",
  "Catuti",
  "Cedro do Abaeté",
  "Central de Minas",
  "Chacara",
  "Chapada do Norte",
  "Chapada Gaúcha",
  "Chiador",
  "Cidade Administrativa Presidente Tancredo Neves",
  "Cidade Verde",
  "Cipotânea",
  "Coimbra",
  "Comendador Gomes",
  "Comendador Valadares",
  "Conceicao da Aparecida",
  "Conceicao da Barra de Minas",
  "Conceicao da Barra de Minas",
  "Conceicao da Barra de Minas",
  "Conceicao do Mato Dentro",
  "Conceicao do Para",
];
